build:
  image: golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=1
    - GOOS=linux
    - GOARCH=amd64
    - CGO_ENABLED=0
  commands:
    - go get
    - go build
    - go test

publish:
  docker:
    username: piscis
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: piscis/drone-bash
    when:
      branch: master

plugin:
  name: Bash
  desc: Execute bash commands for deployment
  type: deploy
  image: piscis/drone-bash
  labels:
    - deployment
    - bash
